[package]
name = "navigator-back"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "macros", "postgres", "sqlite", "any", "uuid"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.219", features = ["derive"] }
env_logger = "0.11.8"
chrono = "0.4.42"
log = "0.4.29"
openid = "0.18.3"
reqwest = "0.12.28"
actix-session = "0.11.0"
actix-cors = "0.7.1"
config = "0.15.19"
rust_decimal = "1.39.0"
url = "2.5.7"
uuid = { version = "1.19.0", features = ["v4"] }
