ALTER TABLE IF EXISTS users ADD COLUMN first_name VARCHAR (255) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS users ADD COLUMN last_name VARCHAR (255) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS users ADD COLUMN email VARCHAR (255);
